/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/kinobi-so/kinobi
 */

import {
  containsBytes,
  getU8Encoder,
  type Address,
  type ReadonlyUint8Array,
} from '@solana/web3.js';
import {
  type ParsedAdminRegisterStMintInstruction,
  type ParsedAdminSetNewAdminInstruction,
  type ParsedAdminSetParametersInstruction,
  type ParsedAdminSetStMintInstruction,
  type ParsedAdminSetTieBreakerInstruction,
  type ParsedAdminSetWeightInstruction,
  type ParsedCastVoteInstruction,
  type ParsedCloseEpochAccountInstruction,
  type ParsedInitializeBallotBoxInstruction,
  type ParsedInitializeConfigInstruction,
  type ParsedInitializeEpochSnapshotInstruction,
  type ParsedInitializeEpochStateInstruction,
  type ParsedInitializeOperatorSnapshotInstruction,
  type ParsedInitializeVaultRegistryInstruction,
  type ParsedInitializeWeightTableInstruction,
  type ParsedReallocBallotBoxInstruction,
  type ParsedReallocVaultRegistryInstruction,
  type ParsedReallocWeightTableInstruction,
  type ParsedRegisterVaultInstruction,
  type ParsedSetEpochWeightsInstruction,
  type ParsedSnapshotVaultOperatorDelegationInstruction,
} from '../instructions';

export const JITO_TIP_ROUTER_PROGRAM_ADDRESS =
  'RouterBmuRBkPUbgEDMtdvTZ75GBdSREZR5uGUxxxpb' as Address<'RouterBmuRBkPUbgEDMtdvTZ75GBdSREZR5uGUxxxpb'>;

export enum JitoTipRouterAccount {
  BallotBox,
  Config,
  ConsensusResult,
  EpochMarker,
  EpochSnapshot,
  OperatorSnapshot,
  EpochState,
  VaultRegistry,
  WeightTable,
}

export enum JitoTipRouterInstruction {
  InitializeConfig,
  InitializeVaultRegistry,
  ReallocVaultRegistry,
  RegisterVault,
  InitializeEpochState,
  InitializeWeightTable,
  SetEpochWeights,
  ReallocWeightTable,
  InitializeEpochSnapshot,
  InitializeOperatorSnapshot,
  SnapshotVaultOperatorDelegation,
  InitializeBallotBox,
  ReallocBallotBox,
  CastVote,
  CloseEpochAccount,
  AdminSetParameters,
  AdminSetNewAdmin,
  AdminSetTieBreaker,
  AdminSetWeight,
  AdminRegisterStMint,
  AdminSetStMint,
}

export function identifyJitoTipRouterInstruction(
  instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array
): JitoTipRouterInstruction {
  const data = 'data' in instruction ? instruction.data : instruction;
  if (containsBytes(data, getU8Encoder().encode(0), 0)) {
    return JitoTipRouterInstruction.InitializeConfig;
  }
  if (containsBytes(data, getU8Encoder().encode(1), 0)) {
    return JitoTipRouterInstruction.InitializeVaultRegistry;
  }
  if (containsBytes(data, getU8Encoder().encode(2), 0)) {
    return JitoTipRouterInstruction.ReallocVaultRegistry;
  }
  if (containsBytes(data, getU8Encoder().encode(3), 0)) {
    return JitoTipRouterInstruction.RegisterVault;
  }
  if (containsBytes(data, getU8Encoder().encode(4), 0)) {
    return JitoTipRouterInstruction.InitializeEpochState;
  }
  if (containsBytes(data, getU8Encoder().encode(5), 0)) {
    return JitoTipRouterInstruction.InitializeWeightTable;
  }
  if (containsBytes(data, getU8Encoder().encode(6), 0)) {
    return JitoTipRouterInstruction.SetEpochWeights;
  }
  if (containsBytes(data, getU8Encoder().encode(7), 0)) {
    return JitoTipRouterInstruction.ReallocWeightTable;
  }
  if (containsBytes(data, getU8Encoder().encode(8), 0)) {
    return JitoTipRouterInstruction.InitializeEpochSnapshot;
  }
  if (containsBytes(data, getU8Encoder().encode(9), 0)) {
    return JitoTipRouterInstruction.InitializeOperatorSnapshot;
  }
  if (containsBytes(data, getU8Encoder().encode(10), 0)) {
    return JitoTipRouterInstruction.SnapshotVaultOperatorDelegation;
  }
  if (containsBytes(data, getU8Encoder().encode(11), 0)) {
    return JitoTipRouterInstruction.InitializeBallotBox;
  }
  if (containsBytes(data, getU8Encoder().encode(12), 0)) {
    return JitoTipRouterInstruction.ReallocBallotBox;
  }
  if (containsBytes(data, getU8Encoder().encode(13), 0)) {
    return JitoTipRouterInstruction.CastVote;
  }
  if (containsBytes(data, getU8Encoder().encode(14), 0)) {
    return JitoTipRouterInstruction.CloseEpochAccount;
  }
  if (containsBytes(data, getU8Encoder().encode(15), 0)) {
    return JitoTipRouterInstruction.AdminSetParameters;
  }
  if (containsBytes(data, getU8Encoder().encode(16), 0)) {
    return JitoTipRouterInstruction.AdminSetNewAdmin;
  }
  if (containsBytes(data, getU8Encoder().encode(17), 0)) {
    return JitoTipRouterInstruction.AdminSetTieBreaker;
  }
  if (containsBytes(data, getU8Encoder().encode(18), 0)) {
    return JitoTipRouterInstruction.AdminSetWeight;
  }
  if (containsBytes(data, getU8Encoder().encode(19), 0)) {
    return JitoTipRouterInstruction.AdminRegisterStMint;
  }
  if (containsBytes(data, getU8Encoder().encode(20), 0)) {
    return JitoTipRouterInstruction.AdminSetStMint;
  }
  throw new Error(
    'The provided instruction could not be identified as a jitoTipRouter instruction.'
  );
}

export type ParsedJitoTipRouterInstruction<
  TProgram extends string = 'RouterBmuRBkPUbgEDMtdvTZ75GBdSREZR5uGUxxxpb',
> =
  | ({
      instructionType: JitoTipRouterInstruction.InitializeConfig;
    } & ParsedInitializeConfigInstruction<TProgram>)
  | ({
      instructionType: JitoTipRouterInstruction.InitializeVaultRegistry;
    } & ParsedInitializeVaultRegistryInstruction<TProgram>)
  | ({
      instructionType: JitoTipRouterInstruction.ReallocVaultRegistry;
    } & ParsedReallocVaultRegistryInstruction<TProgram>)
  | ({
      instructionType: JitoTipRouterInstruction.RegisterVault;
    } & ParsedRegisterVaultInstruction<TProgram>)
  | ({
      instructionType: JitoTipRouterInstruction.InitializeEpochState;
    } & ParsedInitializeEpochStateInstruction<TProgram>)
  | ({
      instructionType: JitoTipRouterInstruction.InitializeWeightTable;
    } & ParsedInitializeWeightTableInstruction<TProgram>)
  | ({
      instructionType: JitoTipRouterInstruction.SetEpochWeights;
    } & ParsedSetEpochWeightsInstruction<TProgram>)
  | ({
      instructionType: JitoTipRouterInstruction.ReallocWeightTable;
    } & ParsedReallocWeightTableInstruction<TProgram>)
  | ({
      instructionType: JitoTipRouterInstruction.InitializeEpochSnapshot;
    } & ParsedInitializeEpochSnapshotInstruction<TProgram>)
  | ({
      instructionType: JitoTipRouterInstruction.InitializeOperatorSnapshot;
    } & ParsedInitializeOperatorSnapshotInstruction<TProgram>)
  | ({
      instructionType: JitoTipRouterInstruction.SnapshotVaultOperatorDelegation;
    } & ParsedSnapshotVaultOperatorDelegationInstruction<TProgram>)
  | ({
      instructionType: JitoTipRouterInstruction.InitializeBallotBox;
    } & ParsedInitializeBallotBoxInstruction<TProgram>)
  | ({
      instructionType: JitoTipRouterInstruction.ReallocBallotBox;
    } & ParsedReallocBallotBoxInstruction<TProgram>)
  | ({
      instructionType: JitoTipRouterInstruction.CastVote;
    } & ParsedCastVoteInstruction<TProgram>)
  | ({
      instructionType: JitoTipRouterInstruction.CloseEpochAccount;
    } & ParsedCloseEpochAccountInstruction<TProgram>)
  | ({
      instructionType: JitoTipRouterInstruction.AdminSetParameters;
    } & ParsedAdminSetParametersInstruction<TProgram>)
  | ({
      instructionType: JitoTipRouterInstruction.AdminSetNewAdmin;
    } & ParsedAdminSetNewAdminInstruction<TProgram>)
  | ({
      instructionType: JitoTipRouterInstruction.AdminSetTieBreaker;
    } & ParsedAdminSetTieBreakerInstruction<TProgram>)
  | ({
      instructionType: JitoTipRouterInstruction.AdminSetWeight;
    } & ParsedAdminSetWeightInstruction<TProgram>)
  | ({
      instructionType: JitoTipRouterInstruction.AdminRegisterStMint;
    } & ParsedAdminRegisterStMintInstruction<TProgram>)
  | ({
      instructionType: JitoTipRouterInstruction.AdminSetStMint;
    } & ParsedAdminSetStMintInstruction<TProgram>);
