/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/kinobi-so/kinobi
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU128Decoder,
  getU128Encoder,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/web3.js';

export type StakeWeights = { stakeWeight: bigint };

export type StakeWeightsArgs = { stakeWeight: number | bigint };

export function getStakeWeightsEncoder(): Encoder<StakeWeightsArgs> {
  return getStructEncoder([['stakeWeight', getU128Encoder()]]);
}

export function getStakeWeightsDecoder(): Decoder<StakeWeights> {
  return getStructDecoder([['stakeWeight', getU128Decoder()]]);
}

export function getStakeWeightsCodec(): Codec<StakeWeightsArgs, StakeWeights> {
  return combineCodec(getStakeWeightsEncoder(), getStakeWeightsDecoder());
}
