/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/kinobi-so/kinobi
 */

import {
  combineCodec,
  getArrayDecoder,
  getArrayEncoder,
  getStructDecoder,
  getStructEncoder,
  getU128Decoder,
  getU128Encoder,
  getU8Decoder,
  getU8Encoder,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/web3.js';

export type StakeWeights = {
  stakeWeight: bigint;
  reservedForNcnFeeGroupStakeWeights: Array<number>;
};

export type StakeWeightsArgs = {
  stakeWeight: number | bigint;
  reservedForNcnFeeGroupStakeWeights: Array<number>;
};

export function getStakeWeightsEncoder(): Encoder<StakeWeightsArgs> {
  return getStructEncoder([
    ['stakeWeight', getU128Encoder()],
    [
      'reservedForNcnFeeGroupStakeWeights',
      getArrayEncoder(getU8Encoder(), { size: 128 }),
    ],
  ]);
}

export function getStakeWeightsDecoder(): Decoder<StakeWeights> {
  return getStructDecoder([
    ['stakeWeight', getU128Decoder()],
    [
      'reservedForNcnFeeGroupStakeWeights',
      getArrayDecoder(getU8Decoder(), { size: 128 }),
    ],
  ]);
}

export function getStakeWeightsCodec(): Codec<StakeWeightsArgs, StakeWeights> {
  return combineCodec(getStakeWeightsEncoder(), getStakeWeightsDecoder());
}
