/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/kinobi-so/kinobi
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/web3.js';
import {
  getStakeWeightsDecoder,
  getStakeWeightsEncoder,
  type StakeWeights,
  type StakeWeightsArgs,
} from '.';

export type VaultOperatorStakeWeight = {
  vault: Address;
  vaultIndex: bigint;
  stakeWeight: StakeWeights;
};

export type VaultOperatorStakeWeightArgs = {
  vault: Address;
  vaultIndex: number | bigint;
  stakeWeight: StakeWeightsArgs;
};

export function getVaultOperatorStakeWeightEncoder(): Encoder<VaultOperatorStakeWeightArgs> {
  return getStructEncoder([
    ['vault', getAddressEncoder()],
    ['vaultIndex', getU64Encoder()],
    ['stakeWeight', getStakeWeightsEncoder()],
  ]);
}

export function getVaultOperatorStakeWeightDecoder(): Decoder<VaultOperatorStakeWeight> {
  return getStructDecoder([
    ['vault', getAddressDecoder()],
    ['vaultIndex', getU64Decoder()],
    ['stakeWeight', getStakeWeightsDecoder()],
  ]);
}

export function getVaultOperatorStakeWeightCodec(): Codec<
  VaultOperatorStakeWeightArgs,
  VaultOperatorStakeWeight
> {
  return combineCodec(
    getVaultOperatorStakeWeightEncoder(),
    getVaultOperatorStakeWeightDecoder()
  );
}
