/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/kinobi-so/kinobi
 */

import {
  isProgramError,
  type Address,
  type SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM,
  type SolanaError,
} from '@solana/web3.js';
import { NCN_PROGRAM_PROGRAM_ADDRESS } from '../programs';

/** NoValidBallots: No valid Ballot */
export const NCN_PROGRAM_ERROR__NO_VALID_BALLOTS = 0x0; // 0
/** DenominatorIsZero: Zero in the denominator */
export const NCN_PROGRAM_ERROR__DENOMINATOR_IS_ZERO = 0x2100; // 8448
/** ArithmeticOverflow: Overflow */
export const NCN_PROGRAM_ERROR__ARITHMETIC_OVERFLOW = 0x2101; // 8449
/** ArithmeticUnderflowError: Underflow */
export const NCN_PROGRAM_ERROR__ARITHMETIC_UNDERFLOW_ERROR = 0x2102; // 8450
/** ArithmeticFloorError: Floor Overflow */
export const NCN_PROGRAM_ERROR__ARITHMETIC_FLOOR_ERROR = 0x2103; // 8451
/** ModuloOverflow: Modulo Overflow */
export const NCN_PROGRAM_ERROR__MODULO_OVERFLOW = 0x2104; // 8452
/** NewPreciseNumberError: New precise number error */
export const NCN_PROGRAM_ERROR__NEW_PRECISE_NUMBER_ERROR = 0x2105; // 8453
/** CastToImpreciseNumberError: Cast to imprecise number error */
export const NCN_PROGRAM_ERROR__CAST_TO_IMPRECISE_NUMBER_ERROR = 0x2106; // 8454
/** CastToU64Error: Cast to u64 error */
export const NCN_PROGRAM_ERROR__CAST_TO_U64_ERROR = 0x2107; // 8455
/** CastToU128Error: Cast to u128 error */
export const NCN_PROGRAM_ERROR__CAST_TO_U128_ERROR = 0x2108; // 8456
/** IncorrectWeightTableAdmin: Incorrect weight table admin */
export const NCN_PROGRAM_ERROR__INCORRECT_WEIGHT_TABLE_ADMIN = 0x2200; // 8704
/** DuplicateMintsInTable: Duplicate mints in table */
export const NCN_PROGRAM_ERROR__DUPLICATE_MINTS_IN_TABLE = 0x2201; // 8705
/** NoMintsInTable: There are no mints in the table */
export const NCN_PROGRAM_ERROR__NO_MINTS_IN_TABLE = 0x2202; // 8706
/** TableNotInitialized: Table not initialized */
export const NCN_PROGRAM_ERROR__TABLE_NOT_INITIALIZED = 0x2203; // 8707
/** RegistryNotInitialized: Registry not initialized */
export const NCN_PROGRAM_ERROR__REGISTRY_NOT_INITIALIZED = 0x2204; // 8708
/** NoVaultsInRegistry: There are no vaults in the registry */
export const NCN_PROGRAM_ERROR__NO_VAULTS_IN_REGISTRY = 0x2205; // 8709
/** VaultNotInRegistry: Vault not in weight table registry */
export const NCN_PROGRAM_ERROR__VAULT_NOT_IN_REGISTRY = 0x2206; // 8710
/** MintInTable: Mint is already in the table */
export const NCN_PROGRAM_ERROR__MINT_IN_TABLE = 0x2207; // 8711
/** TooManyMintsForTable: Too many mints for table */
export const NCN_PROGRAM_ERROR__TOO_MANY_MINTS_FOR_TABLE = 0x2208; // 8712
/** TooManyVaultsForRegistry: Too many vaults for registry */
export const NCN_PROGRAM_ERROR__TOO_MANY_VAULTS_FOR_REGISTRY = 0x2209; // 8713
/** WeightTableAlreadyInitialized: Weight table already initialized */
export const NCN_PROGRAM_ERROR__WEIGHT_TABLE_ALREADY_INITIALIZED = 0x220a; // 8714
/** CannotCreateFutureWeightTables: Cannnot create future weight tables */
export const NCN_PROGRAM_ERROR__CANNOT_CREATE_FUTURE_WEIGHT_TABLES = 0x220b; // 8715
/** WeightMintsDoNotMatchLength: Weight mints do not match - length */
export const NCN_PROGRAM_ERROR__WEIGHT_MINTS_DO_NOT_MATCH_LENGTH = 0x220c; // 8716
/** WeightMintsDoNotMatchMintHash: Weight mints do not match - mint hash */
export const NCN_PROGRAM_ERROR__WEIGHT_MINTS_DO_NOT_MATCH_MINT_HASH = 0x220d; // 8717
/** InvalidMintForWeightTable: Invalid mint for weight table */
export const NCN_PROGRAM_ERROR__INVALID_MINT_FOR_WEIGHT_TABLE = 0x220e; // 8718
/** ConfigMintsNotUpdated: Config supported mints do not match NCN Vault Count */
export const NCN_PROGRAM_ERROR__CONFIG_MINTS_NOT_UPDATED = 0x220f; // 8719
/** ConfigMintListFull: NCN config vaults are at capacity */
export const NCN_PROGRAM_ERROR__CONFIG_MINT_LIST_FULL = 0x2210; // 8720
/** VaultRegistryListFull: Vault Registry mints are at capacity */
export const NCN_PROGRAM_ERROR__VAULT_REGISTRY_LIST_FULL = 0x2211; // 8721
/** VaultRegistryVaultLocked: Vault registry are locked for the epoch */
export const NCN_PROGRAM_ERROR__VAULT_REGISTRY_VAULT_LOCKED = 0x2212; // 8722
/** VaultIndexAlreadyInUse: Vault index already in use by a different mint */
export const NCN_PROGRAM_ERROR__VAULT_INDEX_ALREADY_IN_USE = 0x2213; // 8723
/** MintEntryNotFound: Mint Entry not found */
export const NCN_PROGRAM_ERROR__MINT_ENTRY_NOT_FOUND = 0x2214; // 8724
/** FeeCapExceeded: Fee cap exceeded */
export const NCN_PROGRAM_ERROR__FEE_CAP_EXCEEDED = 0x2215; // 8725
/** TotalFeesCannotBeZero: Total fees cannot be 0 */
export const NCN_PROGRAM_ERROR__TOTAL_FEES_CANNOT_BE_ZERO = 0x2216; // 8726
/** DefaultDaoWallet: Protocol wallet cannot be default */
export const NCN_PROGRAM_ERROR__DEFAULT_DAO_WALLET = 0x2217; // 8727
/** DefaultNcnWallet: NCN Fee wallet cannot be default */
export const NCN_PROGRAM_ERROR__DEFAULT_NCN_WALLET = 0x2218; // 8728
/** IncorrectNcnAdmin: Incorrect NCN Admin */
export const NCN_PROGRAM_ERROR__INCORRECT_NCN_ADMIN = 0x2219; // 8729
/** IncorrectNcn: Incorrect NCN */
export const NCN_PROGRAM_ERROR__INCORRECT_NCN = 0x221a; // 8730
/** IncorrectFeeAdmin: Incorrect fee admin */
export const NCN_PROGRAM_ERROR__INCORRECT_FEE_ADMIN = 0x221b; // 8731
/** WeightTableNotFinalized: Weight table not finalized */
export const NCN_PROGRAM_ERROR__WEIGHT_TABLE_NOT_FINALIZED = 0x221c; // 8732
/** WeightNotFound: Weight not found */
export const NCN_PROGRAM_ERROR__WEIGHT_NOT_FOUND = 0x221d; // 8733
/** NoOperators: No operators in ncn */
export const NCN_PROGRAM_ERROR__NO_OPERATORS = 0x221e; // 8734
/** VaultOperatorDelegationFinalized: Vault operator delegation is already finalized - should not happen */
export const NCN_PROGRAM_ERROR__VAULT_OPERATOR_DELEGATION_FINALIZED = 0x221f; // 8735
/** OperatorFinalized: Operator is already finalized - should not happen */
export const NCN_PROGRAM_ERROR__OPERATOR_FINALIZED = 0x2220; // 8736
/** TooManyVaultOperatorDelegations: Too many vault operator delegations */
export const NCN_PROGRAM_ERROR__TOO_MANY_VAULT_OPERATOR_DELEGATIONS = 0x2221; // 8737
/** DuplicateVaultOperatorDelegation: Duplicate vault operator delegation */
export const NCN_PROGRAM_ERROR__DUPLICATE_VAULT_OPERATOR_DELEGATION = 0x2222; // 8738
/** DuplicateVoteCast: Duplicate Vote Cast */
export const NCN_PROGRAM_ERROR__DUPLICATE_VOTE_CAST = 0x2223; // 8739
/** CannotVoteWithZeroStake: Cannot Vote With Zero Delegation */
export const NCN_PROGRAM_ERROR__CANNOT_VOTE_WITH_ZERO_STAKE = 0x2224; // 8740
/** OperatorAlreadyVoted: Operator Already Voted */
export const NCN_PROGRAM_ERROR__OPERATOR_ALREADY_VOTED = 0x2225; // 8741
/** OperatorVotesFull: Operator votes full */
export const NCN_PROGRAM_ERROR__OPERATOR_VOTES_FULL = 0x2226; // 8742
/** BallotTallyFull: Merkle root tally full */
export const NCN_PROGRAM_ERROR__BALLOT_TALLY_FULL = 0x2227; // 8743
/** BallotTallyNotFoundFull: Ballot tally not found */
export const NCN_PROGRAM_ERROR__BALLOT_TALLY_NOT_FOUND_FULL = 0x2228; // 8744
/** BallotTallyNotEmpty: Ballot tally not empty */
export const NCN_PROGRAM_ERROR__BALLOT_TALLY_NOT_EMPTY = 0x2229; // 8745
/** ConsensusAlreadyReached: Consensus already reached, cannot change vote */
export const NCN_PROGRAM_ERROR__CONSENSUS_ALREADY_REACHED = 0x222a; // 8746
/** ConsensusNotReached: Consensus not reached */
export const NCN_PROGRAM_ERROR__CONSENSUS_NOT_REACHED = 0x222b; // 8747
/** EpochSnapshotNotFinalized: Epoch snapshot not finalized */
export const NCN_PROGRAM_ERROR__EPOCH_SNAPSHOT_NOT_FINALIZED = 0x222c; // 8748
/** VotingNotValid: Voting not valid, too many slots after consensus reached */
export const NCN_PROGRAM_ERROR__VOTING_NOT_VALID = 0x222d; // 8749
/** TieBreakerAdminInvalid: Tie breaker admin invalid */
export const NCN_PROGRAM_ERROR__TIE_BREAKER_ADMIN_INVALID = 0x222e; // 8750
/** VotingNotFinalized: Voting not finalized */
export const NCN_PROGRAM_ERROR__VOTING_NOT_FINALIZED = 0x222f; // 8751
/** TieBreakerNotInPriorVotes: Tie breaking ballot must be one of the prior votes */
export const NCN_PROGRAM_ERROR__TIE_BREAKER_NOT_IN_PRIOR_VOTES = 0x2230; // 8752
/** InvalidMerkleProof: Invalid merkle proof */
export const NCN_PROGRAM_ERROR__INVALID_MERKLE_PROOF = 0x2231; // 8753
/** InvalidOperatorVoter: Operator voter needs to sign its vote */
export const NCN_PROGRAM_ERROR__INVALID_OPERATOR_VOTER = 0x2232; // 8754
/** InvalidNcnFeeGroup: Not a valid NCN fee group */
export const NCN_PROGRAM_ERROR__INVALID_NCN_FEE_GROUP = 0x2233; // 8755
/** InvalidBaseFeeGroup: Not a valid base fee group */
export const NCN_PROGRAM_ERROR__INVALID_BASE_FEE_GROUP = 0x2234; // 8756
/** OperatorRewardListFull: Operator reward list full */
export const NCN_PROGRAM_ERROR__OPERATOR_REWARD_LIST_FULL = 0x2235; // 8757
/** OperatorRewardNotFound: Operator Reward not found */
export const NCN_PROGRAM_ERROR__OPERATOR_REWARD_NOT_FOUND = 0x2236; // 8758
/** VaultRewardNotFound: Vault Reward not found */
export const NCN_PROGRAM_ERROR__VAULT_REWARD_NOT_FOUND = 0x2237; // 8759
/** DestinationMismatch: Destination mismatch */
export const NCN_PROGRAM_ERROR__DESTINATION_MISMATCH = 0x2238; // 8760
/** NcnRewardRouteNotFound: Ncn reward route not found */
export const NCN_PROGRAM_ERROR__NCN_REWARD_ROUTE_NOT_FOUND = 0x2239; // 8761
/** FeeNotActive: Fee not active */
export const NCN_PROGRAM_ERROR__FEE_NOT_ACTIVE = 0x223a; // 8762
/** NoRewards: No rewards to distribute */
export const NCN_PROGRAM_ERROR__NO_REWARDS = 0x223b; // 8763
/** WeightNotSet: Weight not set */
export const NCN_PROGRAM_ERROR__WEIGHT_NOT_SET = 0x223c; // 8764
/** RouterStillRouting: Router still routing */
export const NCN_PROGRAM_ERROR__ROUTER_STILL_ROUTING = 0x223d; // 8765
/** InvalidEpochsBeforeStall: Invalid epochs before stall */
export const NCN_PROGRAM_ERROR__INVALID_EPOCHS_BEFORE_STALL = 0x223e; // 8766
/** InvalidEpochsBeforeClose: Invalid epochs before accounts can close */
export const NCN_PROGRAM_ERROR__INVALID_EPOCHS_BEFORE_CLOSE = 0x223f; // 8767
/** InvalidSlotsAfterConsensus: Invalid slots after consensus */
export const NCN_PROGRAM_ERROR__INVALID_SLOTS_AFTER_CONSENSUS = 0x2240; // 8768
/** VaultNeedsUpdate: Vault needs to be updated */
export const NCN_PROGRAM_ERROR__VAULT_NEEDS_UPDATE = 0x2241; // 8769
/** InvalidAccountStatus: Invalid Account Status */
export const NCN_PROGRAM_ERROR__INVALID_ACCOUNT_STATUS = 0x2242; // 8770
/** AccountAlreadyInitialized: Account already initialized */
export const NCN_PROGRAM_ERROR__ACCOUNT_ALREADY_INITIALIZED = 0x2243; // 8771
/** BadBallot: Cannot vote with uninitialized account */
export const NCN_PROGRAM_ERROR__BAD_BALLOT = 0x2244; // 8772
/** VotingIsNotOver: Cannot route until voting is over */
export const NCN_PROGRAM_ERROR__VOTING_IS_NOT_OVER = 0x2245; // 8773
/** OperatorIsNotInSnapshot: Operator is not in snapshot */
export const NCN_PROGRAM_ERROR__OPERATOR_IS_NOT_IN_SNAPSHOT = 0x2246; // 8774
/** InvalidAccountToCloseDiscriminator: Invalid account_to_close Discriminator */
export const NCN_PROGRAM_ERROR__INVALID_ACCOUNT_TO_CLOSE_DISCRIMINATOR = 0x2247; // 8775
/** CannotCloseAccount: Cannot close account */
export const NCN_PROGRAM_ERROR__CANNOT_CLOSE_ACCOUNT = 0x2248; // 8776
/** CannotCloseAccountAlreadyClosed: Cannot close account - Already closed */
export const NCN_PROGRAM_ERROR__CANNOT_CLOSE_ACCOUNT_ALREADY_CLOSED = 0x2249; // 8777
/** CannotCloseAccountNotEnoughEpochs: Cannot close account - Not enough epochs have passed since consensus reached */
export const NCN_PROGRAM_ERROR__CANNOT_CLOSE_ACCOUNT_NOT_ENOUGH_EPOCHS = 0x224a; // 8778
/** CannotCloseAccountNoReceiverProvided: Cannot close account - No receiver provided */
export const NCN_PROGRAM_ERROR__CANNOT_CLOSE_ACCOUNT_NO_RECEIVER_PROVIDED = 0x224b; // 8779
/** CannotCloseAccountNoEnoughAccounts: Cannot close account - Not enough accounts */
export const NCN_PROGRAM_ERROR__CANNOT_CLOSE_ACCOUNT_NO_ENOUGH_ACCOUNTS = 0x224c; // 8780
/** CannotCloseEpochStateAccount: Cannot close epoch state account - Epoch state needs all other accounts to be closed first */
export const NCN_PROGRAM_ERROR__CANNOT_CLOSE_EPOCH_STATE_ACCOUNT = 0x224d; // 8781
/** InvalidNCNFeeWallet: Invalid NCN Fee wallet */
export const NCN_PROGRAM_ERROR__INVALID_N_C_N_FEE_WALLET = 0x224e; // 8782
/** EpochIsClosingDown: Epoch is closing down */
export const NCN_PROGRAM_ERROR__EPOCH_IS_CLOSING_DOWN = 0x224f; // 8783
/** MarkerExists: Marker exists */
export const NCN_PROGRAM_ERROR__MARKER_EXISTS = 0x2250; // 8784

export type NcnProgramError =
  | typeof NCN_PROGRAM_ERROR__ACCOUNT_ALREADY_INITIALIZED
  | typeof NCN_PROGRAM_ERROR__ARITHMETIC_FLOOR_ERROR
  | typeof NCN_PROGRAM_ERROR__ARITHMETIC_OVERFLOW
  | typeof NCN_PROGRAM_ERROR__ARITHMETIC_UNDERFLOW_ERROR
  | typeof NCN_PROGRAM_ERROR__BAD_BALLOT
  | typeof NCN_PROGRAM_ERROR__BALLOT_TALLY_FULL
  | typeof NCN_PROGRAM_ERROR__BALLOT_TALLY_NOT_EMPTY
  | typeof NCN_PROGRAM_ERROR__BALLOT_TALLY_NOT_FOUND_FULL
  | typeof NCN_PROGRAM_ERROR__CANNOT_CLOSE_ACCOUNT
  | typeof NCN_PROGRAM_ERROR__CANNOT_CLOSE_ACCOUNT_ALREADY_CLOSED
  | typeof NCN_PROGRAM_ERROR__CANNOT_CLOSE_ACCOUNT_NO_ENOUGH_ACCOUNTS
  | typeof NCN_PROGRAM_ERROR__CANNOT_CLOSE_ACCOUNT_NO_RECEIVER_PROVIDED
  | typeof NCN_PROGRAM_ERROR__CANNOT_CLOSE_ACCOUNT_NOT_ENOUGH_EPOCHS
  | typeof NCN_PROGRAM_ERROR__CANNOT_CLOSE_EPOCH_STATE_ACCOUNT
  | typeof NCN_PROGRAM_ERROR__CANNOT_CREATE_FUTURE_WEIGHT_TABLES
  | typeof NCN_PROGRAM_ERROR__CANNOT_VOTE_WITH_ZERO_STAKE
  | typeof NCN_PROGRAM_ERROR__CAST_TO_IMPRECISE_NUMBER_ERROR
  | typeof NCN_PROGRAM_ERROR__CAST_TO_U128_ERROR
  | typeof NCN_PROGRAM_ERROR__CAST_TO_U64_ERROR
  | typeof NCN_PROGRAM_ERROR__CONFIG_MINT_LIST_FULL
  | typeof NCN_PROGRAM_ERROR__CONFIG_MINTS_NOT_UPDATED
  | typeof NCN_PROGRAM_ERROR__CONSENSUS_ALREADY_REACHED
  | typeof NCN_PROGRAM_ERROR__CONSENSUS_NOT_REACHED
  | typeof NCN_PROGRAM_ERROR__DEFAULT_DAO_WALLET
  | typeof NCN_PROGRAM_ERROR__DEFAULT_NCN_WALLET
  | typeof NCN_PROGRAM_ERROR__DENOMINATOR_IS_ZERO
  | typeof NCN_PROGRAM_ERROR__DESTINATION_MISMATCH
  | typeof NCN_PROGRAM_ERROR__DUPLICATE_MINTS_IN_TABLE
  | typeof NCN_PROGRAM_ERROR__DUPLICATE_VAULT_OPERATOR_DELEGATION
  | typeof NCN_PROGRAM_ERROR__DUPLICATE_VOTE_CAST
  | typeof NCN_PROGRAM_ERROR__EPOCH_IS_CLOSING_DOWN
  | typeof NCN_PROGRAM_ERROR__EPOCH_SNAPSHOT_NOT_FINALIZED
  | typeof NCN_PROGRAM_ERROR__FEE_CAP_EXCEEDED
  | typeof NCN_PROGRAM_ERROR__FEE_NOT_ACTIVE
  | typeof NCN_PROGRAM_ERROR__INCORRECT_FEE_ADMIN
  | typeof NCN_PROGRAM_ERROR__INCORRECT_NCN
  | typeof NCN_PROGRAM_ERROR__INCORRECT_NCN_ADMIN
  | typeof NCN_PROGRAM_ERROR__INCORRECT_WEIGHT_TABLE_ADMIN
  | typeof NCN_PROGRAM_ERROR__INVALID_ACCOUNT_STATUS
  | typeof NCN_PROGRAM_ERROR__INVALID_ACCOUNT_TO_CLOSE_DISCRIMINATOR
  | typeof NCN_PROGRAM_ERROR__INVALID_BASE_FEE_GROUP
  | typeof NCN_PROGRAM_ERROR__INVALID_EPOCHS_BEFORE_CLOSE
  | typeof NCN_PROGRAM_ERROR__INVALID_EPOCHS_BEFORE_STALL
  | typeof NCN_PROGRAM_ERROR__INVALID_MERKLE_PROOF
  | typeof NCN_PROGRAM_ERROR__INVALID_MINT_FOR_WEIGHT_TABLE
  | typeof NCN_PROGRAM_ERROR__INVALID_NCN_FEE_GROUP
  | typeof NCN_PROGRAM_ERROR__INVALID_N_C_N_FEE_WALLET
  | typeof NCN_PROGRAM_ERROR__INVALID_OPERATOR_VOTER
  | typeof NCN_PROGRAM_ERROR__INVALID_SLOTS_AFTER_CONSENSUS
  | typeof NCN_PROGRAM_ERROR__MARKER_EXISTS
  | typeof NCN_PROGRAM_ERROR__MINT_ENTRY_NOT_FOUND
  | typeof NCN_PROGRAM_ERROR__MINT_IN_TABLE
  | typeof NCN_PROGRAM_ERROR__MODULO_OVERFLOW
  | typeof NCN_PROGRAM_ERROR__NCN_REWARD_ROUTE_NOT_FOUND
  | typeof NCN_PROGRAM_ERROR__NEW_PRECISE_NUMBER_ERROR
  | typeof NCN_PROGRAM_ERROR__NO_MINTS_IN_TABLE
  | typeof NCN_PROGRAM_ERROR__NO_OPERATORS
  | typeof NCN_PROGRAM_ERROR__NO_REWARDS
  | typeof NCN_PROGRAM_ERROR__NO_VALID_BALLOTS
  | typeof NCN_PROGRAM_ERROR__NO_VAULTS_IN_REGISTRY
  | typeof NCN_PROGRAM_ERROR__OPERATOR_ALREADY_VOTED
  | typeof NCN_PROGRAM_ERROR__OPERATOR_FINALIZED
  | typeof NCN_PROGRAM_ERROR__OPERATOR_IS_NOT_IN_SNAPSHOT
  | typeof NCN_PROGRAM_ERROR__OPERATOR_REWARD_LIST_FULL
  | typeof NCN_PROGRAM_ERROR__OPERATOR_REWARD_NOT_FOUND
  | typeof NCN_PROGRAM_ERROR__OPERATOR_VOTES_FULL
  | typeof NCN_PROGRAM_ERROR__REGISTRY_NOT_INITIALIZED
  | typeof NCN_PROGRAM_ERROR__ROUTER_STILL_ROUTING
  | typeof NCN_PROGRAM_ERROR__TABLE_NOT_INITIALIZED
  | typeof NCN_PROGRAM_ERROR__TIE_BREAKER_ADMIN_INVALID
  | typeof NCN_PROGRAM_ERROR__TIE_BREAKER_NOT_IN_PRIOR_VOTES
  | typeof NCN_PROGRAM_ERROR__TOO_MANY_MINTS_FOR_TABLE
  | typeof NCN_PROGRAM_ERROR__TOO_MANY_VAULT_OPERATOR_DELEGATIONS
  | typeof NCN_PROGRAM_ERROR__TOO_MANY_VAULTS_FOR_REGISTRY
  | typeof NCN_PROGRAM_ERROR__TOTAL_FEES_CANNOT_BE_ZERO
  | typeof NCN_PROGRAM_ERROR__VAULT_INDEX_ALREADY_IN_USE
  | typeof NCN_PROGRAM_ERROR__VAULT_NEEDS_UPDATE
  | typeof NCN_PROGRAM_ERROR__VAULT_NOT_IN_REGISTRY
  | typeof NCN_PROGRAM_ERROR__VAULT_OPERATOR_DELEGATION_FINALIZED
  | typeof NCN_PROGRAM_ERROR__VAULT_REGISTRY_LIST_FULL
  | typeof NCN_PROGRAM_ERROR__VAULT_REGISTRY_VAULT_LOCKED
  | typeof NCN_PROGRAM_ERROR__VAULT_REWARD_NOT_FOUND
  | typeof NCN_PROGRAM_ERROR__VOTING_IS_NOT_OVER
  | typeof NCN_PROGRAM_ERROR__VOTING_NOT_FINALIZED
  | typeof NCN_PROGRAM_ERROR__VOTING_NOT_VALID
  | typeof NCN_PROGRAM_ERROR__WEIGHT_MINTS_DO_NOT_MATCH_LENGTH
  | typeof NCN_PROGRAM_ERROR__WEIGHT_MINTS_DO_NOT_MATCH_MINT_HASH
  | typeof NCN_PROGRAM_ERROR__WEIGHT_NOT_FOUND
  | typeof NCN_PROGRAM_ERROR__WEIGHT_NOT_SET
  | typeof NCN_PROGRAM_ERROR__WEIGHT_TABLE_ALREADY_INITIALIZED
  | typeof NCN_PROGRAM_ERROR__WEIGHT_TABLE_NOT_FINALIZED;

let ncnProgramErrorMessages: Record<NcnProgramError, string> | undefined;
if (process.env.NODE_ENV !== 'production') {
  ncnProgramErrorMessages = {
    [NCN_PROGRAM_ERROR__ACCOUNT_ALREADY_INITIALIZED]: `Account already initialized`,
    [NCN_PROGRAM_ERROR__ARITHMETIC_FLOOR_ERROR]: `Floor Overflow`,
    [NCN_PROGRAM_ERROR__ARITHMETIC_OVERFLOW]: `Overflow`,
    [NCN_PROGRAM_ERROR__ARITHMETIC_UNDERFLOW_ERROR]: `Underflow`,
    [NCN_PROGRAM_ERROR__BAD_BALLOT]: `Cannot vote with uninitialized account`,
    [NCN_PROGRAM_ERROR__BALLOT_TALLY_FULL]: `Merkle root tally full`,
    [NCN_PROGRAM_ERROR__BALLOT_TALLY_NOT_EMPTY]: `Ballot tally not empty`,
    [NCN_PROGRAM_ERROR__BALLOT_TALLY_NOT_FOUND_FULL]: `Ballot tally not found`,
    [NCN_PROGRAM_ERROR__CANNOT_CLOSE_ACCOUNT]: `Cannot close account`,
    [NCN_PROGRAM_ERROR__CANNOT_CLOSE_ACCOUNT_ALREADY_CLOSED]: `Cannot close account - Already closed`,
    [NCN_PROGRAM_ERROR__CANNOT_CLOSE_ACCOUNT_NO_ENOUGH_ACCOUNTS]: `Cannot close account - Not enough accounts`,
    [NCN_PROGRAM_ERROR__CANNOT_CLOSE_ACCOUNT_NO_RECEIVER_PROVIDED]: `Cannot close account - No receiver provided`,
    [NCN_PROGRAM_ERROR__CANNOT_CLOSE_ACCOUNT_NOT_ENOUGH_EPOCHS]: `Cannot close account - Not enough epochs have passed since consensus reached`,
    [NCN_PROGRAM_ERROR__CANNOT_CLOSE_EPOCH_STATE_ACCOUNT]: `Cannot close epoch state account - Epoch state needs all other accounts to be closed first`,
    [NCN_PROGRAM_ERROR__CANNOT_CREATE_FUTURE_WEIGHT_TABLES]: `Cannnot create future weight tables`,
    [NCN_PROGRAM_ERROR__CANNOT_VOTE_WITH_ZERO_STAKE]: `Cannot Vote With Zero Delegation`,
    [NCN_PROGRAM_ERROR__CAST_TO_IMPRECISE_NUMBER_ERROR]: `Cast to imprecise number error`,
    [NCN_PROGRAM_ERROR__CAST_TO_U128_ERROR]: `Cast to u128 error`,
    [NCN_PROGRAM_ERROR__CAST_TO_U64_ERROR]: `Cast to u64 error`,
    [NCN_PROGRAM_ERROR__CONFIG_MINT_LIST_FULL]: `NCN config vaults are at capacity`,
    [NCN_PROGRAM_ERROR__CONFIG_MINTS_NOT_UPDATED]: `Config supported mints do not match NCN Vault Count`,
    [NCN_PROGRAM_ERROR__CONSENSUS_ALREADY_REACHED]: `Consensus already reached, cannot change vote`,
    [NCN_PROGRAM_ERROR__CONSENSUS_NOT_REACHED]: `Consensus not reached`,
    [NCN_PROGRAM_ERROR__DEFAULT_DAO_WALLET]: `Protocol wallet cannot be default`,
    [NCN_PROGRAM_ERROR__DEFAULT_NCN_WALLET]: `NCN Fee wallet cannot be default`,
    [NCN_PROGRAM_ERROR__DENOMINATOR_IS_ZERO]: `Zero in the denominator`,
    [NCN_PROGRAM_ERROR__DESTINATION_MISMATCH]: `Destination mismatch`,
    [NCN_PROGRAM_ERROR__DUPLICATE_MINTS_IN_TABLE]: `Duplicate mints in table`,
    [NCN_PROGRAM_ERROR__DUPLICATE_VAULT_OPERATOR_DELEGATION]: `Duplicate vault operator delegation`,
    [NCN_PROGRAM_ERROR__DUPLICATE_VOTE_CAST]: `Duplicate Vote Cast`,
    [NCN_PROGRAM_ERROR__EPOCH_IS_CLOSING_DOWN]: `Epoch is closing down`,
    [NCN_PROGRAM_ERROR__EPOCH_SNAPSHOT_NOT_FINALIZED]: `Epoch snapshot not finalized`,
    [NCN_PROGRAM_ERROR__FEE_CAP_EXCEEDED]: `Fee cap exceeded`,
    [NCN_PROGRAM_ERROR__FEE_NOT_ACTIVE]: `Fee not active`,
    [NCN_PROGRAM_ERROR__INCORRECT_FEE_ADMIN]: `Incorrect fee admin`,
    [NCN_PROGRAM_ERROR__INCORRECT_NCN]: `Incorrect NCN`,
    [NCN_PROGRAM_ERROR__INCORRECT_NCN_ADMIN]: `Incorrect NCN Admin`,
    [NCN_PROGRAM_ERROR__INCORRECT_WEIGHT_TABLE_ADMIN]: `Incorrect weight table admin`,
    [NCN_PROGRAM_ERROR__INVALID_ACCOUNT_STATUS]: `Invalid Account Status`,
    [NCN_PROGRAM_ERROR__INVALID_ACCOUNT_TO_CLOSE_DISCRIMINATOR]: `Invalid account_to_close Discriminator`,
    [NCN_PROGRAM_ERROR__INVALID_BASE_FEE_GROUP]: `Not a valid base fee group`,
    [NCN_PROGRAM_ERROR__INVALID_EPOCHS_BEFORE_CLOSE]: `Invalid epochs before accounts can close`,
    [NCN_PROGRAM_ERROR__INVALID_EPOCHS_BEFORE_STALL]: `Invalid epochs before stall`,
    [NCN_PROGRAM_ERROR__INVALID_MERKLE_PROOF]: `Invalid merkle proof`,
    [NCN_PROGRAM_ERROR__INVALID_MINT_FOR_WEIGHT_TABLE]: `Invalid mint for weight table`,
    [NCN_PROGRAM_ERROR__INVALID_NCN_FEE_GROUP]: `Not a valid NCN fee group`,
    [NCN_PROGRAM_ERROR__INVALID_N_C_N_FEE_WALLET]: `Invalid NCN Fee wallet`,
    [NCN_PROGRAM_ERROR__INVALID_OPERATOR_VOTER]: `Operator voter needs to sign its vote`,
    [NCN_PROGRAM_ERROR__INVALID_SLOTS_AFTER_CONSENSUS]: `Invalid slots after consensus`,
    [NCN_PROGRAM_ERROR__MARKER_EXISTS]: `Marker exists`,
    [NCN_PROGRAM_ERROR__MINT_ENTRY_NOT_FOUND]: `Mint Entry not found`,
    [NCN_PROGRAM_ERROR__MINT_IN_TABLE]: `Mint is already in the table`,
    [NCN_PROGRAM_ERROR__MODULO_OVERFLOW]: `Modulo Overflow`,
    [NCN_PROGRAM_ERROR__NCN_REWARD_ROUTE_NOT_FOUND]: `Ncn reward route not found`,
    [NCN_PROGRAM_ERROR__NEW_PRECISE_NUMBER_ERROR]: `New precise number error`,
    [NCN_PROGRAM_ERROR__NO_MINTS_IN_TABLE]: `There are no mints in the table`,
    [NCN_PROGRAM_ERROR__NO_OPERATORS]: `No operators in ncn`,
    [NCN_PROGRAM_ERROR__NO_REWARDS]: `No rewards to distribute`,
    [NCN_PROGRAM_ERROR__NO_VALID_BALLOTS]: `No valid Ballot`,
    [NCN_PROGRAM_ERROR__NO_VAULTS_IN_REGISTRY]: `There are no vaults in the registry`,
    [NCN_PROGRAM_ERROR__OPERATOR_ALREADY_VOTED]: `Operator Already Voted`,
    [NCN_PROGRAM_ERROR__OPERATOR_FINALIZED]: `Operator is already finalized - should not happen`,
    [NCN_PROGRAM_ERROR__OPERATOR_IS_NOT_IN_SNAPSHOT]: `Operator is not in snapshot`,
    [NCN_PROGRAM_ERROR__OPERATOR_REWARD_LIST_FULL]: `Operator reward list full`,
    [NCN_PROGRAM_ERROR__OPERATOR_REWARD_NOT_FOUND]: `Operator Reward not found`,
    [NCN_PROGRAM_ERROR__OPERATOR_VOTES_FULL]: `Operator votes full`,
    [NCN_PROGRAM_ERROR__REGISTRY_NOT_INITIALIZED]: `Registry not initialized`,
    [NCN_PROGRAM_ERROR__ROUTER_STILL_ROUTING]: `Router still routing`,
    [NCN_PROGRAM_ERROR__TABLE_NOT_INITIALIZED]: `Table not initialized`,
    [NCN_PROGRAM_ERROR__TIE_BREAKER_ADMIN_INVALID]: `Tie breaker admin invalid`,
    [NCN_PROGRAM_ERROR__TIE_BREAKER_NOT_IN_PRIOR_VOTES]: `Tie breaking ballot must be one of the prior votes`,
    [NCN_PROGRAM_ERROR__TOO_MANY_MINTS_FOR_TABLE]: `Too many mints for table`,
    [NCN_PROGRAM_ERROR__TOO_MANY_VAULT_OPERATOR_DELEGATIONS]: `Too many vault operator delegations`,
    [NCN_PROGRAM_ERROR__TOO_MANY_VAULTS_FOR_REGISTRY]: `Too many vaults for registry`,
    [NCN_PROGRAM_ERROR__TOTAL_FEES_CANNOT_BE_ZERO]: `Total fees cannot be 0`,
    [NCN_PROGRAM_ERROR__VAULT_INDEX_ALREADY_IN_USE]: `Vault index already in use by a different mint`,
    [NCN_PROGRAM_ERROR__VAULT_NEEDS_UPDATE]: `Vault needs to be updated`,
    [NCN_PROGRAM_ERROR__VAULT_NOT_IN_REGISTRY]: `Vault not in weight table registry`,
    [NCN_PROGRAM_ERROR__VAULT_OPERATOR_DELEGATION_FINALIZED]: `Vault operator delegation is already finalized - should not happen`,
    [NCN_PROGRAM_ERROR__VAULT_REGISTRY_LIST_FULL]: `Vault Registry mints are at capacity`,
    [NCN_PROGRAM_ERROR__VAULT_REGISTRY_VAULT_LOCKED]: `Vault registry are locked for the epoch`,
    [NCN_PROGRAM_ERROR__VAULT_REWARD_NOT_FOUND]: `Vault Reward not found`,
    [NCN_PROGRAM_ERROR__VOTING_IS_NOT_OVER]: `Cannot route until voting is over`,
    [NCN_PROGRAM_ERROR__VOTING_NOT_FINALIZED]: `Voting not finalized`,
    [NCN_PROGRAM_ERROR__VOTING_NOT_VALID]: `Voting not valid, too many slots after consensus reached`,
    [NCN_PROGRAM_ERROR__WEIGHT_MINTS_DO_NOT_MATCH_LENGTH]: `Weight mints do not match - length`,
    [NCN_PROGRAM_ERROR__WEIGHT_MINTS_DO_NOT_MATCH_MINT_HASH]: `Weight mints do not match - mint hash`,
    [NCN_PROGRAM_ERROR__WEIGHT_NOT_FOUND]: `Weight not found`,
    [NCN_PROGRAM_ERROR__WEIGHT_NOT_SET]: `Weight not set`,
    [NCN_PROGRAM_ERROR__WEIGHT_TABLE_ALREADY_INITIALIZED]: `Weight table already initialized`,
    [NCN_PROGRAM_ERROR__WEIGHT_TABLE_NOT_FINALIZED]: `Weight table not finalized`,
  };
}

export function getNcnProgramErrorMessage(code: NcnProgramError): string {
  if (process.env.NODE_ENV !== 'production') {
    return (ncnProgramErrorMessages as Record<NcnProgramError, string>)[code];
  }

  return 'Error message not available in production bundles.';
}

export function isNcnProgramError<TProgramErrorCode extends NcnProgramError>(
  error: unknown,
  transactionMessage: {
    instructions: Record<number, { programAddress: Address }>;
  },
  code?: TProgramErrorCode
): error is SolanaError<typeof SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM> &
  Readonly<{ context: Readonly<{ code: TProgramErrorCode }> }> {
  return isProgramError<TProgramErrorCode>(
    error,
    transactionMessage,
    NCN_PROGRAM_PROGRAM_ADDRESS,
    code
  );
}
