/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/kinobi-so/kinobi
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlyAccount,
  type WritableAccount,
} from '@solana/web3.js';
import { NCN_PROGRAM_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const INITIALIZE_OPERATOR_VAULT_REWARD_ROUTER_DISCRIMINATOR = 19;

export function getInitializeOperatorVaultRewardRouterDiscriminatorBytes() {
  return getU8Encoder().encode(
    INITIALIZE_OPERATOR_VAULT_REWARD_ROUTER_DISCRIMINATOR
  );
}

export type InitializeOperatorVaultRewardRouterInstruction<
  TProgram extends string = typeof NCN_PROGRAM_PROGRAM_ADDRESS,
  TAccountEpochMarker extends string | IAccountMeta<string> = string,
  TAccountEpochState extends string | IAccountMeta<string> = string,
  TAccountNcn extends string | IAccountMeta<string> = string,
  TAccountOperator extends string | IAccountMeta<string> = string,
  TAccountOperatorSnapshot extends string | IAccountMeta<string> = string,
  TAccountOperatorVaultRewardRouter extends
    | string
    | IAccountMeta<string> = string,
  TAccountOperatorVaultRewardReceiver extends
    | string
    | IAccountMeta<string> = string,
  TAccountAccountPayer extends string | IAccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | IAccountMeta<string> = '11111111111111111111111111111111',
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountEpochMarker extends string
        ? ReadonlyAccount<TAccountEpochMarker>
        : TAccountEpochMarker,
      TAccountEpochState extends string
        ? WritableAccount<TAccountEpochState>
        : TAccountEpochState,
      TAccountNcn extends string ? ReadonlyAccount<TAccountNcn> : TAccountNcn,
      TAccountOperator extends string
        ? ReadonlyAccount<TAccountOperator>
        : TAccountOperator,
      TAccountOperatorSnapshot extends string
        ? ReadonlyAccount<TAccountOperatorSnapshot>
        : TAccountOperatorSnapshot,
      TAccountOperatorVaultRewardRouter extends string
        ? WritableAccount<TAccountOperatorVaultRewardRouter>
        : TAccountOperatorVaultRewardRouter,
      TAccountOperatorVaultRewardReceiver extends string
        ? WritableAccount<TAccountOperatorVaultRewardReceiver>
        : TAccountOperatorVaultRewardReceiver,
      TAccountAccountPayer extends string
        ? WritableAccount<TAccountAccountPayer>
        : TAccountAccountPayer,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type InitializeOperatorVaultRewardRouterInstructionData = {
  discriminator: number;
  epoch: bigint;
};

export type InitializeOperatorVaultRewardRouterInstructionDataArgs = {
  epoch: number | bigint;
};

export function getInitializeOperatorVaultRewardRouterInstructionDataEncoder(): Encoder<InitializeOperatorVaultRewardRouterInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', getU8Encoder()],
      ['epoch', getU64Encoder()],
    ]),
    (value) => ({
      ...value,
      discriminator: INITIALIZE_OPERATOR_VAULT_REWARD_ROUTER_DISCRIMINATOR,
    })
  );
}

export function getInitializeOperatorVaultRewardRouterInstructionDataDecoder(): Decoder<InitializeOperatorVaultRewardRouterInstructionData> {
  return getStructDecoder([
    ['discriminator', getU8Decoder()],
    ['epoch', getU64Decoder()],
  ]);
}

export function getInitializeOperatorVaultRewardRouterInstructionDataCodec(): Codec<
  InitializeOperatorVaultRewardRouterInstructionDataArgs,
  InitializeOperatorVaultRewardRouterInstructionData
> {
  return combineCodec(
    getInitializeOperatorVaultRewardRouterInstructionDataEncoder(),
    getInitializeOperatorVaultRewardRouterInstructionDataDecoder()
  );
}

export type InitializeOperatorVaultRewardRouterInput<
  TAccountEpochMarker extends string = string,
  TAccountEpochState extends string = string,
  TAccountNcn extends string = string,
  TAccountOperator extends string = string,
  TAccountOperatorSnapshot extends string = string,
  TAccountOperatorVaultRewardRouter extends string = string,
  TAccountOperatorVaultRewardReceiver extends string = string,
  TAccountAccountPayer extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  epochMarker: Address<TAccountEpochMarker>;
  epochState: Address<TAccountEpochState>;
  ncn: Address<TAccountNcn>;
  operator: Address<TAccountOperator>;
  operatorSnapshot: Address<TAccountOperatorSnapshot>;
  operatorVaultRewardRouter: Address<TAccountOperatorVaultRewardRouter>;
  operatorVaultRewardReceiver: Address<TAccountOperatorVaultRewardReceiver>;
  accountPayer: Address<TAccountAccountPayer>;
  systemProgram?: Address<TAccountSystemProgram>;
  epoch: InitializeOperatorVaultRewardRouterInstructionDataArgs['epoch'];
};

export function getInitializeOperatorVaultRewardRouterInstruction<
  TAccountEpochMarker extends string,
  TAccountEpochState extends string,
  TAccountNcn extends string,
  TAccountOperator extends string,
  TAccountOperatorSnapshot extends string,
  TAccountOperatorVaultRewardRouter extends string,
  TAccountOperatorVaultRewardReceiver extends string,
  TAccountAccountPayer extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof NCN_PROGRAM_PROGRAM_ADDRESS,
>(
  input: InitializeOperatorVaultRewardRouterInput<
    TAccountEpochMarker,
    TAccountEpochState,
    TAccountNcn,
    TAccountOperator,
    TAccountOperatorSnapshot,
    TAccountOperatorVaultRewardRouter,
    TAccountOperatorVaultRewardReceiver,
    TAccountAccountPayer,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): InitializeOperatorVaultRewardRouterInstruction<
  TProgramAddress,
  TAccountEpochMarker,
  TAccountEpochState,
  TAccountNcn,
  TAccountOperator,
  TAccountOperatorSnapshot,
  TAccountOperatorVaultRewardRouter,
  TAccountOperatorVaultRewardReceiver,
  TAccountAccountPayer,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? NCN_PROGRAM_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    epochMarker: { value: input.epochMarker ?? null, isWritable: false },
    epochState: { value: input.epochState ?? null, isWritable: true },
    ncn: { value: input.ncn ?? null, isWritable: false },
    operator: { value: input.operator ?? null, isWritable: false },
    operatorSnapshot: {
      value: input.operatorSnapshot ?? null,
      isWritable: false,
    },
    operatorVaultRewardRouter: {
      value: input.operatorVaultRewardRouter ?? null,
      isWritable: true,
    },
    operatorVaultRewardReceiver: {
      value: input.operatorVaultRewardReceiver ?? null,
      isWritable: true,
    },
    accountPayer: { value: input.accountPayer ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.epochMarker),
      getAccountMeta(accounts.epochState),
      getAccountMeta(accounts.ncn),
      getAccountMeta(accounts.operator),
      getAccountMeta(accounts.operatorSnapshot),
      getAccountMeta(accounts.operatorVaultRewardRouter),
      getAccountMeta(accounts.operatorVaultRewardReceiver),
      getAccountMeta(accounts.accountPayer),
      getAccountMeta(accounts.systemProgram),
    ],
    programAddress,
    data: getInitializeOperatorVaultRewardRouterInstructionDataEncoder().encode(
      args as InitializeOperatorVaultRewardRouterInstructionDataArgs
    ),
  } as InitializeOperatorVaultRewardRouterInstruction<
    TProgramAddress,
    TAccountEpochMarker,
    TAccountEpochState,
    TAccountNcn,
    TAccountOperator,
    TAccountOperatorSnapshot,
    TAccountOperatorVaultRewardRouter,
    TAccountOperatorVaultRewardReceiver,
    TAccountAccountPayer,
    TAccountSystemProgram
  >;

  return instruction;
}

export type ParsedInitializeOperatorVaultRewardRouterInstruction<
  TProgram extends string = typeof NCN_PROGRAM_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    epochMarker: TAccountMetas[0];
    epochState: TAccountMetas[1];
    ncn: TAccountMetas[2];
    operator: TAccountMetas[3];
    operatorSnapshot: TAccountMetas[4];
    operatorVaultRewardRouter: TAccountMetas[5];
    operatorVaultRewardReceiver: TAccountMetas[6];
    accountPayer: TAccountMetas[7];
    systemProgram: TAccountMetas[8];
  };
  data: InitializeOperatorVaultRewardRouterInstructionData;
};

export function parseInitializeOperatorVaultRewardRouterInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>
): ParsedInitializeOperatorVaultRewardRouterInstruction<
  TProgram,
  TAccountMetas
> {
  if (instruction.accounts.length < 9) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      epochMarker: getNextAccount(),
      epochState: getNextAccount(),
      ncn: getNextAccount(),
      operator: getNextAccount(),
      operatorSnapshot: getNextAccount(),
      operatorVaultRewardRouter: getNextAccount(),
      operatorVaultRewardReceiver: getNextAccount(),
      accountPayer: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getInitializeOperatorVaultRewardRouterInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
