/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/kinobi-so/kinobi
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlyAccount,
  type WritableAccount,
} from '@solana/web3.js';
import { NCN_PROGRAM_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const ROUTE_OPERATOR_VAULT_REWARDS_DISCRIMINATOR = 21;

export function getRouteOperatorVaultRewardsDiscriminatorBytes() {
  return getU8Encoder().encode(ROUTE_OPERATOR_VAULT_REWARDS_DISCRIMINATOR);
}

export type RouteOperatorVaultRewardsInstruction<
  TProgram extends string = typeof NCN_PROGRAM_PROGRAM_ADDRESS,
  TAccountEpochState extends string | IAccountMeta<string> = string,
  TAccountNcn extends string | IAccountMeta<string> = string,
  TAccountOperator extends string | IAccountMeta<string> = string,
  TAccountOperatorSnapshot extends string | IAccountMeta<string> = string,
  TAccountOperatorVaultRewardRouter extends
    | string
    | IAccountMeta<string> = string,
  TAccountOperatorVaultRewardReceiver extends
    | string
    | IAccountMeta<string> = string,
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountEpochState extends string
        ? WritableAccount<TAccountEpochState>
        : TAccountEpochState,
      TAccountNcn extends string ? ReadonlyAccount<TAccountNcn> : TAccountNcn,
      TAccountOperator extends string
        ? ReadonlyAccount<TAccountOperator>
        : TAccountOperator,
      TAccountOperatorSnapshot extends string
        ? ReadonlyAccount<TAccountOperatorSnapshot>
        : TAccountOperatorSnapshot,
      TAccountOperatorVaultRewardRouter extends string
        ? WritableAccount<TAccountOperatorVaultRewardRouter>
        : TAccountOperatorVaultRewardRouter,
      TAccountOperatorVaultRewardReceiver extends string
        ? WritableAccount<TAccountOperatorVaultRewardReceiver>
        : TAccountOperatorVaultRewardReceiver,
      ...TRemainingAccounts,
    ]
  >;

export type RouteOperatorVaultRewardsInstructionData = {
  discriminator: number;
  maxIterations: number;
  epoch: bigint;
};

export type RouteOperatorVaultRewardsInstructionDataArgs = {
  maxIterations: number;
  epoch: number | bigint;
};

export function getRouteOperatorVaultRewardsInstructionDataEncoder(): Encoder<RouteOperatorVaultRewardsInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', getU8Encoder()],
      ['maxIterations', getU16Encoder()],
      ['epoch', getU64Encoder()],
    ]),
    (value) => ({
      ...value,
      discriminator: ROUTE_OPERATOR_VAULT_REWARDS_DISCRIMINATOR,
    })
  );
}

export function getRouteOperatorVaultRewardsInstructionDataDecoder(): Decoder<RouteOperatorVaultRewardsInstructionData> {
  return getStructDecoder([
    ['discriminator', getU8Decoder()],
    ['maxIterations', getU16Decoder()],
    ['epoch', getU64Decoder()],
  ]);
}

export function getRouteOperatorVaultRewardsInstructionDataCodec(): Codec<
  RouteOperatorVaultRewardsInstructionDataArgs,
  RouteOperatorVaultRewardsInstructionData
> {
  return combineCodec(
    getRouteOperatorVaultRewardsInstructionDataEncoder(),
    getRouteOperatorVaultRewardsInstructionDataDecoder()
  );
}

export type RouteOperatorVaultRewardsInput<
  TAccountEpochState extends string = string,
  TAccountNcn extends string = string,
  TAccountOperator extends string = string,
  TAccountOperatorSnapshot extends string = string,
  TAccountOperatorVaultRewardRouter extends string = string,
  TAccountOperatorVaultRewardReceiver extends string = string,
> = {
  epochState: Address<TAccountEpochState>;
  ncn: Address<TAccountNcn>;
  operator: Address<TAccountOperator>;
  operatorSnapshot: Address<TAccountOperatorSnapshot>;
  operatorVaultRewardRouter: Address<TAccountOperatorVaultRewardRouter>;
  operatorVaultRewardReceiver: Address<TAccountOperatorVaultRewardReceiver>;
  maxIterations: RouteOperatorVaultRewardsInstructionDataArgs['maxIterations'];
  epoch: RouteOperatorVaultRewardsInstructionDataArgs['epoch'];
};

export function getRouteOperatorVaultRewardsInstruction<
  TAccountEpochState extends string,
  TAccountNcn extends string,
  TAccountOperator extends string,
  TAccountOperatorSnapshot extends string,
  TAccountOperatorVaultRewardRouter extends string,
  TAccountOperatorVaultRewardReceiver extends string,
  TProgramAddress extends Address = typeof NCN_PROGRAM_PROGRAM_ADDRESS,
>(
  input: RouteOperatorVaultRewardsInput<
    TAccountEpochState,
    TAccountNcn,
    TAccountOperator,
    TAccountOperatorSnapshot,
    TAccountOperatorVaultRewardRouter,
    TAccountOperatorVaultRewardReceiver
  >,
  config?: { programAddress?: TProgramAddress }
): RouteOperatorVaultRewardsInstruction<
  TProgramAddress,
  TAccountEpochState,
  TAccountNcn,
  TAccountOperator,
  TAccountOperatorSnapshot,
  TAccountOperatorVaultRewardRouter,
  TAccountOperatorVaultRewardReceiver
> {
  // Program address.
  const programAddress = config?.programAddress ?? NCN_PROGRAM_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    epochState: { value: input.epochState ?? null, isWritable: true },
    ncn: { value: input.ncn ?? null, isWritable: false },
    operator: { value: input.operator ?? null, isWritable: false },
    operatorSnapshot: {
      value: input.operatorSnapshot ?? null,
      isWritable: false,
    },
    operatorVaultRewardRouter: {
      value: input.operatorVaultRewardRouter ?? null,
      isWritable: true,
    },
    operatorVaultRewardReceiver: {
      value: input.operatorVaultRewardReceiver ?? null,
      isWritable: true,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.epochState),
      getAccountMeta(accounts.ncn),
      getAccountMeta(accounts.operator),
      getAccountMeta(accounts.operatorSnapshot),
      getAccountMeta(accounts.operatorVaultRewardRouter),
      getAccountMeta(accounts.operatorVaultRewardReceiver),
    ],
    programAddress,
    data: getRouteOperatorVaultRewardsInstructionDataEncoder().encode(
      args as RouteOperatorVaultRewardsInstructionDataArgs
    ),
  } as RouteOperatorVaultRewardsInstruction<
    TProgramAddress,
    TAccountEpochState,
    TAccountNcn,
    TAccountOperator,
    TAccountOperatorSnapshot,
    TAccountOperatorVaultRewardRouter,
    TAccountOperatorVaultRewardReceiver
  >;

  return instruction;
}

export type ParsedRouteOperatorVaultRewardsInstruction<
  TProgram extends string = typeof NCN_PROGRAM_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    epochState: TAccountMetas[0];
    ncn: TAccountMetas[1];
    operator: TAccountMetas[2];
    operatorSnapshot: TAccountMetas[3];
    operatorVaultRewardRouter: TAccountMetas[4];
    operatorVaultRewardReceiver: TAccountMetas[5];
  };
  data: RouteOperatorVaultRewardsInstructionData;
};

export function parseRouteOperatorVaultRewardsInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>
): ParsedRouteOperatorVaultRewardsInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 6) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      epochState: getNextAccount(),
      ncn: getNextAccount(),
      operator: getNextAccount(),
      operatorSnapshot: getNextAccount(),
      operatorVaultRewardRouter: getNextAccount(),
      operatorVaultRewardReceiver: getNextAccount(),
    },
    data: getRouteOperatorVaultRewardsInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
