/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/kinobi-so/kinobi
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  getAddressDecoder,
  getAddressEncoder,
  getArrayDecoder,
  getArrayEncoder,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  type Account,
  type Address,
  type Codec,
  type Decoder,
  type EncodedAccount,
  type Encoder,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type MaybeAccount,
  type MaybeEncodedAccount,
} from '@solana/web3.js';
import {
  getVaultRewardRouteDecoder,
  getVaultRewardRouteEncoder,
  type VaultRewardRoute,
  type VaultRewardRouteArgs,
} from '../types';

export type OperatorVaultRewardRouter = {
  discriminator: bigint;
  operator: Address;
  ncn: Address;
  epoch: bigint;
  bump: number;
  slotCreated: bigint;
  ncnOperatorIndex: bigint;
  totalRewards: bigint;
  rewardPool: bigint;
  rewardsProcessed: bigint;
  operatorRewards: bigint;
  lastRewardsToProcess: bigint;
  lastVaultOperatorDelegationIndex: number;
  vaultRewardRoutes: Array<VaultRewardRoute>;
};

export type OperatorVaultRewardRouterArgs = {
  discriminator: number | bigint;
  operator: Address;
  ncn: Address;
  epoch: number | bigint;
  bump: number;
  slotCreated: number | bigint;
  ncnOperatorIndex: number | bigint;
  totalRewards: number | bigint;
  rewardPool: number | bigint;
  rewardsProcessed: number | bigint;
  operatorRewards: number | bigint;
  lastRewardsToProcess: number | bigint;
  lastVaultOperatorDelegationIndex: number;
  vaultRewardRoutes: Array<VaultRewardRouteArgs>;
};

export function getOperatorVaultRewardRouterEncoder(): Encoder<OperatorVaultRewardRouterArgs> {
  return getStructEncoder([
    ['discriminator', getU64Encoder()],
    ['operator', getAddressEncoder()],
    ['ncn', getAddressEncoder()],
    ['epoch', getU64Encoder()],
    ['bump', getU8Encoder()],
    ['slotCreated', getU64Encoder()],
    ['ncnOperatorIndex', getU64Encoder()],
    ['totalRewards', getU64Encoder()],
    ['rewardPool', getU64Encoder()],
    ['rewardsProcessed', getU64Encoder()],
    ['operatorRewards', getU64Encoder()],
    ['lastRewardsToProcess', getU64Encoder()],
    ['lastVaultOperatorDelegationIndex', getU16Encoder()],
    [
      'vaultRewardRoutes',
      getArrayEncoder(getVaultRewardRouteEncoder(), { size: 64 }),
    ],
  ]);
}

export function getOperatorVaultRewardRouterDecoder(): Decoder<OperatorVaultRewardRouter> {
  return getStructDecoder([
    ['discriminator', getU64Decoder()],
    ['operator', getAddressDecoder()],
    ['ncn', getAddressDecoder()],
    ['epoch', getU64Decoder()],
    ['bump', getU8Decoder()],
    ['slotCreated', getU64Decoder()],
    ['ncnOperatorIndex', getU64Decoder()],
    ['totalRewards', getU64Decoder()],
    ['rewardPool', getU64Decoder()],
    ['rewardsProcessed', getU64Decoder()],
    ['operatorRewards', getU64Decoder()],
    ['lastRewardsToProcess', getU64Decoder()],
    ['lastVaultOperatorDelegationIndex', getU16Decoder()],
    [
      'vaultRewardRoutes',
      getArrayDecoder(getVaultRewardRouteDecoder(), { size: 64 }),
    ],
  ]);
}

export function getOperatorVaultRewardRouterCodec(): Codec<
  OperatorVaultRewardRouterArgs,
  OperatorVaultRewardRouter
> {
  return combineCodec(
    getOperatorVaultRewardRouterEncoder(),
    getOperatorVaultRewardRouterDecoder()
  );
}

export function decodeOperatorVaultRewardRouter<
  TAddress extends string = string,
>(
  encodedAccount: EncodedAccount<TAddress>
): Account<OperatorVaultRewardRouter, TAddress>;
export function decodeOperatorVaultRewardRouter<
  TAddress extends string = string,
>(
  encodedAccount: MaybeEncodedAccount<TAddress>
): MaybeAccount<OperatorVaultRewardRouter, TAddress>;
export function decodeOperatorVaultRewardRouter<
  TAddress extends string = string,
>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>
):
  | Account<OperatorVaultRewardRouter, TAddress>
  | MaybeAccount<OperatorVaultRewardRouter, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getOperatorVaultRewardRouterDecoder()
  );
}

export async function fetchOperatorVaultRewardRouter<
  TAddress extends string = string,
>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<Account<OperatorVaultRewardRouter, TAddress>> {
  const maybeAccount = await fetchMaybeOperatorVaultRewardRouter(
    rpc,
    address,
    config
  );
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeOperatorVaultRewardRouter<
  TAddress extends string = string,
>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<MaybeAccount<OperatorVaultRewardRouter, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeOperatorVaultRewardRouter(maybeAccount);
}

export async function fetchAllOperatorVaultRewardRouter(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<Account<OperatorVaultRewardRouter>[]> {
  const maybeAccounts = await fetchAllMaybeOperatorVaultRewardRouter(
    rpc,
    addresses,
    config
  );
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeOperatorVaultRewardRouter(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<MaybeAccount<OperatorVaultRewardRouter>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) =>
    decodeOperatorVaultRewardRouter(maybeAccount)
  );
}
