/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/kinobi-so/kinobi
 */

import {
  combineCodec,
  getBoolDecoder,
  getBoolEncoder,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/web3.js';

export type Ballot = { weatherStatus: number; isValid: number };

export type BallotArgs = Ballot;

export function getBallotEncoder(): Encoder<BallotArgs> {
  return getStructEncoder([
    ['weatherStatus', getU8Encoder()],
    ['isValid', getBoolEncoder()],
  ]);
}

export function getBallotDecoder(): Decoder<Ballot> {
  return getStructDecoder([
    ['weatherStatus', getU8Decoder()],
    ['isValid', getBoolDecoder()],
  ]);
}

export function getBallotCodec(): Codec<BallotArgs, Ballot> {
  return combineCodec(getBallotEncoder(), getBallotDecoder());
}
