/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/kinobi-so/kinobi
 */

import {
  combineCodec,
  getArrayDecoder,
  getArrayEncoder,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/web3.js';

export type EpochAccountStatus = {
  epochState: number;
  weightTable: number;
  epochSnapshot: number;
  operatorSnapshot: Array<number>;
  ballotBox: number;
  ncnRewardRouter: number;
  operatorVaultRewardRouter: Array<number>;
};

export type EpochAccountStatusArgs = EpochAccountStatus;

export function getEpochAccountStatusEncoder(): Encoder<EpochAccountStatusArgs> {
  return getStructEncoder([
    ['epochState', getU8Encoder()],
    ['weightTable', getU8Encoder()],
    ['epochSnapshot', getU8Encoder()],
    ['operatorSnapshot', getArrayEncoder(getU8Encoder(), { size: 256 })],
    ['ballotBox', getU8Encoder()],
    ['ncnRewardRouter', getU8Encoder()],
    [
      'operatorVaultRewardRouter',
      getArrayEncoder(getU8Encoder(), { size: 256 }),
    ],
  ]);
}

export function getEpochAccountStatusDecoder(): Decoder<EpochAccountStatus> {
  return getStructDecoder([
    ['epochState', getU8Decoder()],
    ['weightTable', getU8Decoder()],
    ['epochSnapshot', getU8Decoder()],
    ['operatorSnapshot', getArrayDecoder(getU8Decoder(), { size: 256 })],
    ['ballotBox', getU8Decoder()],
    ['ncnRewardRouter', getU8Decoder()],
    [
      'operatorVaultRewardRouter',
      getArrayDecoder(getU8Decoder(), { size: 256 }),
    ],
  ]);
}

export function getEpochAccountStatusCodec(): Codec<
  EpochAccountStatusArgs,
  EpochAccountStatus
> {
  return combineCodec(
    getEpochAccountStatusEncoder(),
    getEpochAccountStatusDecoder()
  );
}
