/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/kinobi-so/kinobi
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/web3.js';
import { getFeesDecoder, getFeesEncoder, type Fees, type FeesArgs } from '.';

export type FeeConfig = {
  protocolFeeWallet: Address;
  ncnFeeWallets: Address;
  fee1: Fees;
  fee2: Fees;
};

export type FeeConfigArgs = {
  protocolFeeWallet: Address;
  ncnFeeWallets: Address;
  fee1: FeesArgs;
  fee2: FeesArgs;
};

export function getFeeConfigEncoder(): Encoder<FeeConfigArgs> {
  return getStructEncoder([
    ['protocolFeeWallet', getAddressEncoder()],
    ['ncnFeeWallets', getAddressEncoder()],
    ['fee1', getFeesEncoder()],
    ['fee2', getFeesEncoder()],
  ]);
}

export function getFeeConfigDecoder(): Decoder<FeeConfig> {
  return getStructDecoder([
    ['protocolFeeWallet', getAddressDecoder()],
    ['ncnFeeWallets', getAddressDecoder()],
    ['fee1', getFeesDecoder()],
    ['fee2', getFeesDecoder()],
  ]);
}

export function getFeeConfigCodec(): Codec<FeeConfigArgs, FeeConfig> {
  return combineCodec(getFeeConfigEncoder(), getFeeConfigDecoder());
}
