/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/kinobi-so/kinobi
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/web3.js';

export type NCNRewardRouterRewards = { rewards: bigint };

export type NCNRewardRouterRewardsArgs = { rewards: number | bigint };

export function getNCNRewardRouterRewardsEncoder(): Encoder<NCNRewardRouterRewardsArgs> {
  return getStructEncoder([['rewards', getU64Encoder()]]);
}

export function getNCNRewardRouterRewardsDecoder(): Decoder<NCNRewardRouterRewards> {
  return getStructDecoder([['rewards', getU64Decoder()]]);
}

export function getNCNRewardRouterRewardsCodec(): Codec<
  NCNRewardRouterRewardsArgs,
  NCNRewardRouterRewards
> {
  return combineCodec(
    getNCNRewardRouterRewardsEncoder(),
    getNCNRewardRouterRewardsDecoder()
  );
}
