/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/kinobi-so/kinobi
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/web3.js';
import {
  getNCNRewardRouterRewardsDecoder,
  getNCNRewardRouterRewardsEncoder,
  type NCNRewardRouterRewards,
  type NCNRewardRouterRewardsArgs,
} from '.';

export type OperatorVaultRewardRoute = {
  operator: Address;
  rewards: NCNRewardRouterRewards;
};

export type OperatorVaultRewardRouteArgs = {
  operator: Address;
  rewards: NCNRewardRouterRewardsArgs;
};

export function getOperatorVaultRewardRouteEncoder(): Encoder<OperatorVaultRewardRouteArgs> {
  return getStructEncoder([
    ['operator', getAddressEncoder()],
    ['rewards', getNCNRewardRouterRewardsEncoder()],
  ]);
}

export function getOperatorVaultRewardRouteDecoder(): Decoder<OperatorVaultRewardRoute> {
  return getStructDecoder([
    ['operator', getAddressDecoder()],
    ['rewards', getNCNRewardRouterRewardsDecoder()],
  ]);
}

export function getOperatorVaultRewardRouteCodec(): Codec<
  OperatorVaultRewardRouteArgs,
  OperatorVaultRewardRoute
> {
  return combineCodec(
    getOperatorVaultRewardRouteEncoder(),
    getOperatorVaultRewardRouteDecoder()
  );
}
