/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/kinobi-so/kinobi
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlyAccount,
  type WritableAccount,
} from '@solana/web3.js';
import { JITO_TIP_ROUTER_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const SET_EPOCH_WEIGHTS_DISCRIMINATOR = 6;

export function getSetEpochWeightsDiscriminatorBytes() {
  return getU8Encoder().encode(SET_EPOCH_WEIGHTS_DISCRIMINATOR);
}

export type SetEpochWeightsInstruction<
  TProgram extends string = typeof JITO_TIP_ROUTER_PROGRAM_ADDRESS,
  TAccountEpochState extends string | IAccountMeta<string> = string,
  TAccountNcn extends string | IAccountMeta<string> = string,
  TAccountVaultRegistry extends string | IAccountMeta<string> = string,
  TAccountWeightTable extends string | IAccountMeta<string> = string,
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountEpochState extends string
        ? WritableAccount<TAccountEpochState>
        : TAccountEpochState,
      TAccountNcn extends string ? ReadonlyAccount<TAccountNcn> : TAccountNcn,
      TAccountVaultRegistry extends string
        ? ReadonlyAccount<TAccountVaultRegistry>
        : TAccountVaultRegistry,
      TAccountWeightTable extends string
        ? WritableAccount<TAccountWeightTable>
        : TAccountWeightTable,
      ...TRemainingAccounts,
    ]
  >;

export type SetEpochWeightsInstructionData = {
  discriminator: number;
  epoch: bigint;
};

export type SetEpochWeightsInstructionDataArgs = { epoch: number | bigint };

export function getSetEpochWeightsInstructionDataEncoder(): Encoder<SetEpochWeightsInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', getU8Encoder()],
      ['epoch', getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: SET_EPOCH_WEIGHTS_DISCRIMINATOR })
  );
}

export function getSetEpochWeightsInstructionDataDecoder(): Decoder<SetEpochWeightsInstructionData> {
  return getStructDecoder([
    ['discriminator', getU8Decoder()],
    ['epoch', getU64Decoder()],
  ]);
}

export function getSetEpochWeightsInstructionDataCodec(): Codec<
  SetEpochWeightsInstructionDataArgs,
  SetEpochWeightsInstructionData
> {
  return combineCodec(
    getSetEpochWeightsInstructionDataEncoder(),
    getSetEpochWeightsInstructionDataDecoder()
  );
}

export type SetEpochWeightsInput<
  TAccountEpochState extends string = string,
  TAccountNcn extends string = string,
  TAccountVaultRegistry extends string = string,
  TAccountWeightTable extends string = string,
> = {
  epochState: Address<TAccountEpochState>;
  ncn: Address<TAccountNcn>;
  vaultRegistry: Address<TAccountVaultRegistry>;
  weightTable: Address<TAccountWeightTable>;
  epoch: SetEpochWeightsInstructionDataArgs['epoch'];
};

export function getSetEpochWeightsInstruction<
  TAccountEpochState extends string,
  TAccountNcn extends string,
  TAccountVaultRegistry extends string,
  TAccountWeightTable extends string,
  TProgramAddress extends Address = typeof JITO_TIP_ROUTER_PROGRAM_ADDRESS,
>(
  input: SetEpochWeightsInput<
    TAccountEpochState,
    TAccountNcn,
    TAccountVaultRegistry,
    TAccountWeightTable
  >,
  config?: { programAddress?: TProgramAddress }
): SetEpochWeightsInstruction<
  TProgramAddress,
  TAccountEpochState,
  TAccountNcn,
  TAccountVaultRegistry,
  TAccountWeightTable
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? JITO_TIP_ROUTER_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    epochState: { value: input.epochState ?? null, isWritable: true },
    ncn: { value: input.ncn ?? null, isWritable: false },
    vaultRegistry: { value: input.vaultRegistry ?? null, isWritable: false },
    weightTable: { value: input.weightTable ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.epochState),
      getAccountMeta(accounts.ncn),
      getAccountMeta(accounts.vaultRegistry),
      getAccountMeta(accounts.weightTable),
    ],
    programAddress,
    data: getSetEpochWeightsInstructionDataEncoder().encode(
      args as SetEpochWeightsInstructionDataArgs
    ),
  } as SetEpochWeightsInstruction<
    TProgramAddress,
    TAccountEpochState,
    TAccountNcn,
    TAccountVaultRegistry,
    TAccountWeightTable
  >;

  return instruction;
}

export type ParsedSetEpochWeightsInstruction<
  TProgram extends string = typeof JITO_TIP_ROUTER_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    epochState: TAccountMetas[0];
    ncn: TAccountMetas[1];
    vaultRegistry: TAccountMetas[2];
    weightTable: TAccountMetas[3];
  };
  data: SetEpochWeightsInstructionData;
};

export function parseSetEpochWeightsInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>
): ParsedSetEpochWeightsInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 4) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      epochState: getNextAccount(),
      ncn: getNextAccount(),
      vaultRegistry: getNextAccount(),
      weightTable: getNextAccount(),
    },
    data: getSetEpochWeightsInstructionDataDecoder().decode(instruction.data),
  };
}
